### ISSUE TITLE
About the `setValue`

### ISSUE THREAD

**Issue by vanpipy** [onlyhom/mobile-select#101]
I am curious about the `setValue` cause there is a `getValue` function, why the `setValue` is missing?

In my opinion, the functions as follows make sence:

* show
* hide
* setTitle
* setValue
* getValue
* destory

so the missing `setValue` confuses me.

Thanks for any response.

**Comment by onlyhom** [comment]
Thanks for your advice, which made me realize that missing setValue would confuse users.

If you want to reset your data now, you can use two methods that are now available: `updateWheel()`(update non-cascading data) and `updateWheels()` (update cascading data).

According to your advice, I will add the `setValue()` method to replace `updateWheel()`/`updateWheels()`.
I'll finish it in a week, Thank you again for your issue.

**Comment by vanpipy** [comment]
Thanks the reply, but maybe i did not get your idea. Because follow the [Functions](https://github.com/onlyhom/mobile-select#functions) described,

<html>
<body>


updateWheel() | sliderIndex, data |   | Re-render the specified wheel
-- | -- | -- | --
updateWheels() | data |   | Re-render the all wheel(Only used in cascading data forma)
getValue() | no-argument |   | Gets the value selected by the component


</body>
</html>

the `getValue` is to get the selected value, the paired `setValue` should to update the selected value programmably. I think the design of the `updateWheel` or `updateWheels` make sense. So, Dose it just add the function `setValue`? And sync the value when invoked the `updateWheel`?

All i thought above, thanks.

**Comment by onlyhom** [comment]
Thanks for your explanation. Now I got it,  you just want to add the `setValue()` method to update the selected value.

But i don't know how to design the exact details of `setValue()`.
Because i'm not sure if you want to update one column or multiple columns of data after invoke `setValue()`.
As I understand, the selected value refers to multiple columns of data (If it's a multi-column selection).

Let's take the example of the [mobile-select demo](https://onlyhom.github.io/mobile-select/demo.html)  to discuss :
1.The first demo has only one column.  If invoke `setValue()`, means update the selected value `['周四']` to a new value, It makes sense.    

2.But in second demo, It has two columns. If we invoke `getValue()` will get value: `['周一', '09:30']`, so the paired method `setValue()` should update both column?

3.The fifth demo is a cascade data demo,if we invoke `getValue` will get value: `[{"id":"2","value":"劳斯莱斯"},{"id":"4","value":"魅影"},{"id":"1","value":"标准版"}]`. There's a question here if update all columns: it will change the value of the parent in the cascade data, It's gonna be weird.

So, I think it makes sense to update the last column.  But if we only need update one column, it's similar to the `updateWheel()` method, and it's not paired with `getValue()`. Because `getValue()` can gets more detailed (multi column) data.

**Comment by vanpipy** [comment]
> 3.The fifth demo is a cascade data demo,if we invoke getValue() will get: [{"id":"2","value":"劳斯莱斯"},{"id":"4","value":"魅影"},{"id":"1","value":"标准版"}]. There's a question here if update all columns: it will change the value of the parent in the cascade data, It's gonna be weird.

If try to `setValue` with `['劳斯莱斯', '魅影', '标准版']` and I think the viewer should match it whether the cascade mode or not. Because the ArrayList like `['劳斯莱斯', '魅影', '标准版']` has an order which from left to right. This order should match any abstract structure step by step to describe something. So the `id` is not the problem.

The problem is the return value of the `getValue`. Anyway, If the `setValue` should be added, the input format should be same with `getValue`. And the `['劳斯莱斯', '魅影', '标准版']` is betther than `[{"id":"2","value":"劳斯莱斯"},{"id":"4","value":"魅影"},{"id":"1","value":"标准版"}]` cause the user dose not need to know anything detail with implement.

**Comment by onlyhom** [comment]
Thanks, I agree with you on this point: 
> If the setValue should be added, the input format should be same with getValue.

But in cascade mode, I think the getValue returns data still need to have ` id ` : `[{"id":"2","value":"劳斯莱斯"},{"id":"4","value":"魅影"},{"id":"1","value":"标准版"}]`.

There are two reasons:
1. It is necessary to support return `id`. In some business scenarios, the back-end only stores `id` in the database, so the front-end only needs to submit the selected `id` without submitting the value when submit the form. Some data source of options data are from the api, `id` is specified by the back-end.
2. In non-cascade mode, also can return `id` when we invoke `getValue()`, You can read [README.md#json-format---non-cascade](https://github.com/onlyhom/mobile-select#json-format---non-cascade) to get detail. 

Therefore, I think `id` does not cause setValue problems, but whether **the parent option can be changed in the cascade mode**. 

让我们拿一个中国省市区数据的级联模式的例子来讨论：

- 假设我们先选择了一个`广东省，广州市，天河区`的数据。 
- 接着，我们想通过`setValue()`来更新数据，根据前面的讨论，此时三列都可以被更改
- 然后，假设通过`setValue()`传入了一个`四川省，成都市，温江区`的新数据 。此时`广东省`就会变为`四川省`，但这个时候广东省原有分类下原有的城市（深圳市、东莞市等）都会属于四川省的分类，而广州市的管辖区(天河区、黄埔区等)就会变为成都市的管辖区。

这样**级联关系就会错乱**，级联数据不合适同时更改一行的数据 。如果真的需要更改选项数据，我认为还是直接使用`updateWheels()`，更新整个数据源会更合适。

**Comment by onlyhom** [comment]
Sorry, I have misunderstood the exact details of `setValue()` again. 

`setValue()` just needs to update the position of the wheel with a specific value, rather than replacing the current wheel position with the specific value. 

So the above example is not appropriate.

Therefore, it also makes sense to add `setValue` to the cascade mode, because instead of replacing the value, it updates the wheel position by specific value.

I hope I got this right this time.

**Comment by vanpipy** [comment]
> Sorry, I have misunderstood the exact details of `setValue()` again.
> 
> `setValue()` just needs to update the position of the wheel with a specific value, rather than replacing the current wheel position with the specific value.
> 
> **So the above example of city options is not appropriate.**
> 
> Therefore, it also makes sense to add `setValue` to the cascade mode, because instead of replacing the value, it updates the wheel position by specific value. And input format should be same with `getValue()`, so parameter with `id` is also necessary.
> 
> I hope I got this right this time.

Yep, that is i want to explain. Thanks your patience :D.

**Comment by onlyhom** [comment]
The `setValue()` method has been added, now you can reinstall mobile-select with version 1.4.0.     
Thanks you for your good idea :D.
